version: "3"
services:

  nginx:
    image: nginx
    build:
      context: ./requirements/nginx/
      args:
        - DOMAIN_NAME
    ports:
      - "443:443"
    networks:
      - network-docker
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
    depends_on:
      - wordpress

  mariadb:
    image: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    networks:
      - network-docker
    restart: always
    volumes:
      - volume-mariadb:/var/lib/mysql

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress/
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WP_URL
      - WP_TITLE
      - WP_SUB_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_PWD
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_PWD
      - WP_USER_EMAIL
    networks:
      - network-docker
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
    depends_on:
      - mariadb

networks:

  network-docker:
    driver: bridge
    name: network-docker

volumes:

  volume-mariadb:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/mariadb
      o: bind
      type: none
    name: volume-mariadb

  volume-wordpress:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/wordpress
      o: bind
      type: none
    name: volume-wordpress
