version: "3"
services:
  nginx:
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - network-nginx
    restart: always
  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - network-mariadb
    restart: always
  wordpress:
    build:
      context: ./requirements/wordpress/
    ports:
      - "9000:9000"
    networks:
      - network-wordpress
    restart: always

networks:
  network-nginx:
    driver: bridge
    name: network-nginx
  network-mariadb:
    driver: bridge
    name: network-mariadb
  network-wordpress:
    driver: bridge
    name: network-wordpress
