version: "3"
services:
  nginx:
    build:
     context: ./requirements/nginx/
    ports:
      - "443:443"
  mariadb:
    build:
     context: ./requirements/mariadb/
     args:
       - MYSQL_DATABASE
       - MYSQL_ROOT
       - MYSQL_ROOT_PASSWORD
       - MYSQL_USER
       - MYSQL_PASSWORD
    ports:
      - "3306:3306"
