version: "3"
services:

  redis:
    image: redis:1.0
    container_name: redis
    build:
      context: ./bonus/redis/
    networks:
      - network-docker
    restart: always
    depends_on:
      - wordpress

  ftp:
    image: ftp:1.0
    container_name: ftp
    build:
      context: ./bonus/vsftpd/
      args:
        - FTP_PATH
        - FTP_USER
        - FTP_PWD
    environment:
      - FTP_PATH
      - FTP_USER
    ports:
      - "21:21"
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
    depends_on:
      - wordpress

  site:
    image: site:1.0
    container_name: site
    build:
      context: ./bonus/site/
    networks:
      - network-docker
    restart: always
    depends_on:
      - nginx

  adminer:
    image: adminer:1.0
    container_name: adminer
    build:
      context: ./bonus/adminer/
    networks:
      - network-docker
    restart: always
    volumes:
      - volume-adminer:/var/www/adminer
    depends_on:
      - mariadb

  nginx:
    image: nginx:1.0
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        - DOMAIN_NAME
    ports:
      - "443:443"
    networks:
      - network-docker
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
      - volume-adminer:/var/www/adminer
    depends_on:
      - wordpress

  mariadb:
    image: mariadb:1.0
    container_name: mariadb
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    networks:
      - network-docker
    restart: always
    volumes:
      - volume-mariadb:/var/lib/mysql

  wordpress:
    image: wordpress:1.0
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
    environment:
      - DOMAIN_NAME
      - REDIS_HOST
      - REDIS_PORT
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WP_URL
      - WP_TITLE
      - WP_SUB_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_PWD
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_PWD
      - WP_USER_EMAIL
    networks:
      - network-docker
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
    depends_on:
      - mariadb

networks:

  network-docker:
    driver: bridge
    name: network-docker

volumes:

  volume-mariadb:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/mariadb
      o: bind
      type: none
    name: volume-mariadb

  volume-wordpress:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/wordpress
      o: bind
      type: none
    name: volume-wordpress

  volume-adminer:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/adminer
      o: bind
      type: none
    name: volume-adminer

