version: "3"
services:

  nginx:
    build:
      context: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - network-nginx
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
    depends_on:
      - wordpress

  mariadb:
    build:
      context: ./requirements/mariadb/
      args:
        - MYSQL_DATABASE
        - MYSQL_ROOT
        - MYSQL_ROOT_PASSWORD
        - MYSQL_USER
        - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - network-mariadb
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress/
    environment:
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - WP_URL
      - WP_TITLE
      - WP_SUB_TITLE
      - WP_ADMIN_USER
      - WP_ADMIN_PWD
      - WP_ADMIN_EMAIL
      - WP_USER
      - WP_USER_PWD
      - WP_USER_EMAIL
    ports:
      - "9000:9000"
    networks:
      - network-wordpress
      - network-mariadb
      - network-nginx
    restart: always
    volumes:
      - volume-wordpress:/var/www/wordpress
    depends_on:
      - mariadb

networks:

  network-nginx:
    driver: bridge
    name: network-nginx
  network-mariadb:
    driver: bridge
    name: network-mariadb
  network-wordpress:
    driver: bridge
    name: network-wordpress

volumes:

  volume-wordpress:
    driver: local
    driver_opts:
      device: ${VOLUME_PATH}/wordpress
      o: bind
      type: none
    name: volume-wordpress
